package org.firstinspires.ftc.teamcode.opmodes.auto;

public enum AutoState {
    SHOOTARTIFACT1, SHOOTARTIFACT2, SHOOTARTIFACT3, INDEXARTIFACT1, INDEXARTIFACT2, INDEXARTIFACT3, MOVEOFFLINE, MOVETOSHOOTINGPOSITION

}
